steps:
  - name: 'mirror.gcr.io/library/golang'
    args: ['go', 'version']
  - name: 'mirror.gcr.io/library/golang'
    args: ['go', 'get', '-u', 'github.com/shuLhan/go-bindata/...', '&&', 'go', 'generate']
    dir: 'cloud_functions/functions'
  - name: 'mirror.gcr.io/library/golang'
    args: ['go', 'test']
    dir: 'cloud_functions/functions'
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'GraphQL-Handler', '--trigger-http', '--runtime', 'go111', '--allow-unauthenticated', '--entry-point', 'HandleGraphQL']
    dir: 'cloud_functions/functions'
